"""link pos refunds to till sessions

Revision ID: 0980f07fde03
Revises: 9c276b0ab9f0
Create Date: 2026-07-06 20:17:24.760807
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0980f07fde03"
down_revision: Union[str, None] = "9c276b0ab9f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("till_session_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_payments_till_session_id"),
        "payments",
        ["till_session_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_payments_till_session_id_till_sessions"),
        "payments",
        "till_sessions",
        ["till_session_id"],
        ["id"],
    )
    op.add_column(
        "sale_returns", sa.Column("till_session_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_sale_returns_till_session_id_till_sessions"),
        "sale_returns",
        "till_sessions",
        ["till_session_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_sale_returns_till_session_id_till_sessions"),
        "sale_returns",
        type_="foreignkey",
    )
    op.drop_column("sale_returns", "till_session_id")
    op.drop_constraint(
        op.f("fk_payments_till_session_id_till_sessions"),
        "payments",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_payments_till_session_id"), table_name="payments")
    op.drop_column("payments", "till_session_id")
    # ### end Alembic commands ###
