"""add customers details to sales tables

Revision ID: 7de05cf6ac41
Revises: bc9d1f8e2a44
Create Date: 2026-08-17 15:13:32.317420
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7de05cf6ac41'
down_revision: Union[str, None] = 'bc9d1f8e2a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
