"""add stock count tables

Revision ID: 9c276b0ab9f0
Revises: 777154bd1cf1
Create Date: 2026-07-06 19:34:07.334471
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "9c276b0ab9f0"
down_revision: Union[str, None] = "777154bd1cf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_counts",
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("count_number", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "approved",
                "cancelled",
                name="stock_count_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
            name=op.f("fk_stock_counts_approved_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_stock_counts_branch_id_branches"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_stock_counts_created_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_counts")),
        sa.UniqueConstraint("count_number", name=op.f("uq_stock_counts_count_number")),
    )
    op.create_index(
        op.f("ix_stock_counts_branch_id"), "stock_counts", ["branch_id"], unique=False
    )
    op.create_table(
        "stock_count_items",
        sa.Column("stock_count_id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("expected_quantity", sa.Integer(), nullable=False),
        sa.Column("counted_quantity", sa.Integer(), nullable=True),
        sa.Column("variance", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "counted_quantity IS NULL OR counted_quantity >= 0",
            name=op.f("ck_stock_count_items_counted_quantity_nonnegative"),
        ),
        sa.CheckConstraint(
            "expected_quantity >= 0",
            name=op.f("ck_stock_count_items_count_expected_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["stock_count_id"],
            ["stock_counts.id"],
            name=op.f("fk_stock_count_items_stock_count_id_stock_counts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_stock_count_items_variant_id_product_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_count_items")),
    )
    op.create_index(
        op.f("ix_stock_count_items_stock_count_id"),
        "stock_count_items",
        ["stock_count_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stock_count_items_stock_count_id"), table_name="stock_count_items"
    )
    op.drop_table("stock_count_items")
    op.drop_index(op.f("ix_stock_counts_branch_id"), table_name="stock_counts")
    op.drop_table("stock_counts")
    # ### end Alembic commands ###
